# git-cliff ~ configuration file | https://git-cliff.org/docs/configuration
[changelog]
# template for the changelog header
header = """
# Ledger Changelog
> [!TIP]
> See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.

All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body | https://keats.github.io/tera/docs/#introduction
body = """
\n---\n
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]($REPO/compare/{{ previous.version }}..{{ version }}) - Released on {{ timestamp | date(format="%Y.%m.%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - Released on {{ timestamp | date(format="%Y.%m.%d") }}
    {% endif %}\
{% else %}\
    ## Unreleased changes
    > [!NOTE]
    > Unreleased changes are the commits present in `master` that have not yet been included in a release. This is the version of the code Ledger will contain when building from source.
    {% raw %}\n{% endraw %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    {%- if group == '<!-- 2 -->🤖 Dependency Updates' -%}
        {% raw %}\n{% endraw %}\
        ### {{ group | striptags | trim | upper_first }}
        <details>
        <ul>
        {% for commit in commits
        | filter(attribute="scope")
        | sort(attribute="scope") %}
            <li> {% if commit.breaking %} [**breaking**]{% endif %}\
                {{ commit.message | capitalize }} - (<a href="$REPO/commit/{{ commit.id }}" target=_blank>{{ commit.id | truncate(length=7, end="") }}</a>) - <em>{{ commit.author.name }}</em></li>
        {%- endfor -%}
        {% raw %}\n{% endraw %}\
        </ul>
        </details><br>
    {% else -%}
        {% raw %}\n{% endraw %}\
        {% if group == '<!-- 0 -->🎉 Initial commit: introducing ledger! 🎉' %}\
            {% for commit in commits %}\
                ### {{ group | striptags | trim }}
                <pre><code class="nohighlight">
                {%- for line in commit.message | split(pat="\n") | slice(start=2) -%}
                    {{ line }}
                {% endfor -%}
                </code></pre>
                <p><small><a href="$REPO/commit/{{ commit.id }}">{{ commit.id | truncate(length=7, end="") }}</a> - <em>{{ commit.author.name }}</em></small></p>
            {% endfor -%}
        {% else -%}
        ### {{ group | striptags | trim | upper_first }}
        {% for commit in commits
            | filter(attribute="scope")
            | sort(attribute="scope") %}
                + **{{ commit.scope | capitalize }}:** {% if commit.breaking %} [**breaking**]{% endif %}\
                    {{ commit.message | split(pat="\n") | first }} ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}) - _{{ commit.author.name }}_)
            {%- endfor -%}
            {% raw %}\n{% endraw %}\
            {%- for commit in commits %}
                {%- if commit.scope -%}
                {% else -%}
                    + {% if commit.breaking %} [**breaking**]{% endif %}\
                        {{ commit.message | split(pat="\n") | first | capitalize }} ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}) - _{{ commit.author.name }}_)
                {% endif -%}
            {% endfor -%}
        {% endif -%}
    {% endif -%}
{% endfor %}\n
"""
# template for the changelog footer
footer = """
"""

trim = true  # remove the leading and trailing whitespace from the templates

# postprocessors
postprocessors = [
    { pattern = '\$REPO', replace = "https://github.com/bvdbasch/ledger" }, # replace repository URL
]

[git]
conventional_commits = true     # parse the commits based on https://www.conventionalcommits.org
filter_unconventional = false   # filter out the commits that are not conventional
split_commits = false           # process each line of a commit as an individual commit
filter_commits = false          # filter out the commits that are not matched by commit parsers
topo_order = false              # sort the tags topologically
sort_commits = "oldest"         # sort the commits inside sections by oldest/newest order
tag_pattern = "[0-9].*"         # pattern for release names

# regex for preprocessing the commit messages
commit_preprocessors = []

# regex for parsing and grouping commits
commit_parsers = [
    { body = ".*security", group = "<!-- 0 -->🚓 Security" },
    { message = "^initial commit", group = "<!-- 0 -->🎉 Initial commit: introducing ledger! 🎉" },
    { message = "^feat", group = "<!-- 0 -->🌄 New Features & Dashboards" },
    { message = "^fix", group = "<!-- 1 -->🪲 Bug Fixes" },
    { message = "^doc", group = "<!-- 1 -->📚 Documentation" },
    { message = "^perf", group = "<!-- 1 -->🏎️ Performance" },
    { message = "^refactor", group = "<!-- 1 -->🚜 Refactoring" },
    { message = "^style", group = "<!-- 1 -->🎨 Style" },
    { message = "^revert", group = "<!-- 1 -->🔙 Revert" },
    { message = "^test", group = "<!-- 1 -->🧪 Tests" },
    { message = "^chore\\(deps\\)", group = "<!-- 2 -->🤖 Dependency Updates" },
    { message = "^ci", group = "<!-- 1 -->🚀 CI/CD" },
    { message = "^build", group = "<!-- 1 -->🚀 CI/CD" },
    { message = "^chore", group = "<!-- 1 -->⚙️ Miscellaneous Chores" },
    { message = ".*", group = "<!-- 1 -->⚙️ Miscellaneous Chores" },
]
